---
# ansible-playbook.yml

- name: Set up Docker and deploy container on Azure VM
  hosts: all
  become: true
  gather_facts: no
  tasks:
    # Update apt packages
    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: yes

    # Install Docker
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    # Start Docker service
    - name: Start service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    # # Copy Dockerfile to VM
    - name: Copy Dockerfile to VM
      ansible.builtin.copy:
        src: ../Dockerfile  # Adjust path if necessary
        dest: /home/rtvjadmin/Dockerfile
        owner: rtvjadmin
        mode: '0644'

    # # Copy application code to VM
    - name: Copy application code to VM
      ansible.builtin.copy:
        src: ../app  # Adjust path if necessary
        dest: /home/rtvjadmin/
        owner: rtvjadmin
        mode: '0644'

    - name: Stop all running containers
      shell: docker stop $(docker ps -q)
      register: stop_result
      changed_when: stop_result.stdout != ""

    # Remove all stopped containers
    - name: Remove all stopped containers
      shell: docker rm $(docker ps -aq)
      register: remove_result
      changed_when: remove_result.stdout != ""

    # Remove all Docker images (optional)
    - name: Remove all Docker images
      shell: docker rmi -f $(docker images -q)
      register: remove_images
      changed_when: remove_images.stdout != ""

    # # Build Docker image
    - name: Build Docker image
      ansible.builtin.command:
        cmd: docker build -t myapp:latest /home/rtvjadmin/

    # # Run Docker container
    - name: Run Docker container
      ansible.builtin.command:
        cmd: docker run -d -p 80:80 myapp:latest
