name: OpenTofu & Ansible Deployment

on:
  push:
    branches:
      - main

jobs:
  opentofu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install OpenTofu (Terraform Alternative)
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Initialize OpenTofu
        run: tofu init
        working-directory: terraforms

      - name: Plan OpenTofu Deployment
        id: plan
        run: tofu plan -out=tfplan
        working-directory: terraforms
        continue-on-error: true  # Prevents stopping if no changes

      - name: Apply OpenTofu Deployment (Only if changes exist)
        if: steps.plan.outcome == 'success'
        run: tofu apply -auto-approve tfplan
        working-directory: terraforms
        continue-on-error: true

  ansible:
    needs: opentofu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Read VM IP
        id: read_vm_ip
        run: echo "VM_IP=172.184.198.156" >> $GITHUB_ENV

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > my-azure-key.pem
          chmod 600 my-azure-key.pem
          ssh-keygen -y -f my-azure-key.pem > my-azure-key.pub
        working-directory: ansible

      - name: Setup Ansible Inventory
        run: |
          echo "[all]" > inventory.ini
          echo "172.184.198.156" > inventory.ini
          echo "[all:vars]" > inventory.ini
          echo "ansible_user=rtvjadmin" > inventory.ini
          echo "ansible_ssh_private_key_file=my-azure-key.pem" > inventory.ini
          echo "ansible_python_interpreter=/usr/bin/python3" > inventory.ini
          echo "ansible_ssh_common_args='-o ServerAliveInterval=60 -o ServerAliveCountMax=3'" > inventory.ini
          echo "ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'" > inventory.ini
        working-directory: ansible

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no -i my-azure-key.pem azureuser@172.184.198.156 "echo SSH Connection Successful"
        working-directory: ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini playbook.yml
        working-directory: ansible

